# 创建ConfigMap对象，会存储在k8s的etcd数据库中
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configs
  namespace: netcore
data:
  appsettings: | 
    {
      "Logging": {
        "LogLevel": {
          "Default": "Warning"
        }
      },
      "AllowedHosts": "www.neobai.com",
      "QQ": {
        "AppId": "5434454",
        "AppSecret": "sfsdmkwe"
      }
    }

