apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-api
  namespace: netcore
  labels:
    name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user-api
  template:
    metadata:
      labels:
        name: user-api
    spec:
      containers:
      - name: user-api
        image: registry.cn-hangzhou.aliyuncs.com/shz/k8s.samples.user.api:1.0.1
        
        # 指定容器需要挂载的目录，secret对象的item将通过文件的方式出现在容器目录中
        volumeMounts:
        - name: secret-user
          mountPath: "/app/secret"
          readOnly: true        
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      
      # 声明挂载的volume，类型为secret对象
      volumes:
      - name: secret-user
        secret:
          secretName: mysecret


---

kind: Service
apiVersion: v1
metadata:
  name: user-api
  namespace: netcore
spec:
  type: NodePort
  ports:
    - port: 10000
      targetPort: 80
  selector:
    name: user-api

---

# 创建secret对象，会存储在k8s的etcd数据库中
kind: Secret
apiVersion: v1
metadata:
  name: mysecret
  namespace: netcore
type: Opaque
data:
  user: YWRtaW4=
  pwd: MTIzNDU2
